<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LTIN593252" failures="1" tests="1" name="Test" time="31.92" errors="0" timestamp="2025-05-12T15:05:26 IST">
  <testcase classname="amazon.VerifyCart" name="VerifyTheProd" time="8.903">
    <failure type="java.lang.AssertionError" message="expected [1] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [0]
at amazon.VerifyCart.VerifyTheProd(VerifyCart.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- VerifyTheProd -->
</testsuite> <!-- Test -->
